# GitHub Actions for building and deploying Node.js app to Azure Web App

name: Build and deploy Node.js app to Azure Web App - quizifygame

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Match your runtime (use 20 for stability)

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip artifact for deployment
        run: |
          mkdir build-output
          cp -r dist package.json package-lock.json node_modules build-output/
          cd build-output
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_796BF07635624167BB1E0D80754E2F27 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2630CE4EAB1C4DEAB39700A2230BE708 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B861A0C2DDE2463E93680849D0AE800C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quizifygame'
          slot-name: 'Production'
          package: .
