name: Build and Deploy to Azure App Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: quizifygame    # Your Azure App Service name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # Path to your app
  NODE_VERSION: '18.x'                # Node.js version to use

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Create deployment package
      run: |
        # Create a clean directory for deployment
        mkdir deployment
        
        # Copy built files
        cp -r dist deployment/
        
        # Copy package.json and package-lock.json
        cp package*.json deployment/
        
        # Copy any other necessary files (like config files, if any)
        # cp -r config deployment/ # uncomment if you have config files
        
        # Install only production dependencies in deployment folder
        cd deployment
        npm ci --only=production
        
        # Create zip file for deployment
        cd ..
        zip -r deployment.zip deployment/
    
    - name: Upload deployment package
      uses: actions/upload-artifact@v4
      with:
        name: deployment-package
        path: deployment.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download deployment package
      uses: actions/download-artifact@v4
      with:
        name: deployment-package
    
    - name: Unzip deployment package
      run: unzip deployment.zip
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment/
